crm/urls.py
from django.urls import path,re_path
from crm.views import consultant,teacher

urlpatterns = [
   # path('customer_list/', views.customer_list, name='custmoer'), # 公户
   path('customer_list/', consultant.CustomerList.as_view(), name='custmoer'), # 公户
   # path('my_customer/', views.customer_list, name='my_customer'), # 公户
   path('my_customer/', consultant.CustomerList.as_view(), name='my_customer'), # 公户
   path('customer/add/', consultant.custmoer, name='add_custmoer'),  # 增加
   path('customer/edit/<edit_id>', consultant.custmoer, name='edit_custmoer'),  # 编辑


   # 展示跟进记录
   re_path(r'consult_record_list/(?P<customer_id>\d+)', consultant.ConsultRecord.as_view(), name='consult_record'),
   # 新增跟进记录
   path('add_consult/', consultant.consult, name='add_record'),
   # 编辑跟进记录
   path('edit_consult/<edit_id>', consultant.consult, name='edit_record'),
   # 展示报名记录
   re_path('enrollment_list/(?P<customer_id>\d+)', consultant.EnrollmentList.as_view(), name='enrollment'),
   # 添加报名记录
   re_path('enrollment/add/(?P<customer_id>\d+)', consultant.enrollment, name='add_enrollment'),
   # 修改报名记录
   re_path('enrollment/edit/(?P<customer_id>\d+)', consultant.enrollmentEdit, name='edit_enrollment'),


   # 展示班级
   re_path(r'class_list/', teacher.ClassList.as_view(), name='class_list'),
   # 新增
   re_path(r'class/add/', teacher.classes, name='add_class'),
   # 编辑
   re_path(r'class/edit/(\d+)', teacher.classes, name='edit_class'),


   # 展示某个课程记录
   re_path(r'course_list/(?P<class_id>\d+)', teacher.course_list.as_view(), name='course_list'),
   # 新增
   re_path(r'course/add/', teacher.course, name='add_course'),
   # 编辑
   re_path(r'course/edit(\d+)', teacher.course, name='edit_course')
]

crm_kxm/urls.py
from django.contrib import admin
from django.urls import path,include
from crm.views import consultant

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', consultant.login),
    path('reg/', consultant.reg),

    path('crm/', include('crm.urls'))
]

crm/models.py
from django.db import models

from django.db import models
from django.contrib import auth
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager,User
from django.utils.translation import ugettext_lazy as _
from multiselectfield import MultiSelectField


course_choices = (('LinuxL', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


class Customer(models.Model):
    """
    客户表
    """
    qq = models.CharField('QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True)
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True, on_delete=models.CASCADE)
    course = MultiSelectField("咨询课程", choices=course_choices)
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")
    network_consult_note = models.TextField(blank=True, null=True, verbose_name='网络咨询师咨询内容')
    date = models.DateTimeField("咨询日期", auto_now_add=True)
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)
    network_consultant = models.ForeignKey('UserProfile', blank=True, null=True, verbose_name='咨询师',
                                           related_name='network_consultant', on_delete=models.CASCADE)
    consultant = models.ForeignKey('UserProfile', verbose_name="销售", related_name='customers', blank=True, null=True,  on_delete=models.CASCADE)
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级", blank=True)



    def __str__(self):
        return "{}({})".format(self.name, self.qq)

    def show_classes(self):
        """class_list 拼接成字符串"""
        return ' | '.join([str(i) for i in self.class_list.all()])

    def show_status(self):
        color_dict = {
            "signed":'green',
            "unregistered":'red',
            "studying":'pink',
            "paid_in_full":'blue'
        }
        return '<span style="background-color: {}; color: white; padding: 3px">{}</span>'.format(color_dict[self.status], self.get_status_display())
    class Meta:
        verbose_name = '客户列表'
        verbose_name_plural = '客户列表'

class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name


class ContractTemplate(models.Model):
    """
    合同模板表
    """
    name = models.CharField("合同名称", max_length=128, unique=True)
    content = models.TextField("合同内容")
    date = models.DateField(auto_now=True)


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")
    campuses = models.ForeignKey('Campuses', verbose_name="校区", on_delete=models.CASCADE)
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)
    contract = models.ForeignKey('ContractTemplate', verbose_name="选择合同模版", blank=True, null=True, on_delete=models.CASCADE)
    teachers = models.ManyToManyField('UserProfile', verbose_name="老师")
    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,
                                  null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')

    def __str__(self):
        return "{}{}({})".format(self.get_course_display(), self.semester, self.campuses)

    def show_teacher(self):
        return "|".join([str(i) for i in self.teachers.all()])

class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户", on_delete=models.CASCADE)
    note = models.TextField(verbose_name="跟进内容...")
    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
    consultant = models.ForeignKey("UserProfile", verbose_name="跟进人", related_name='records', on_delete=models.CASCADE)
    date = models.DateTimeField("跟进日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)


class Enrollment(models.Model):
    """
    报名表
    """

    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
    contract_agreed = models.BooleanField("我已认真阅读完培训协议并同意全部协议内容", default=False)
    contract_approved = models.BooleanField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", default=False)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    customer = models.ForeignKey('Customer', verbose_name='客户名称', on_delete=models.CASCADE)
    school = models.ForeignKey('Campuses', on_delete=models.CASCADE)
    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级", on_delete=models.CASCADE)

    class Meta:
        unique_together = ('enrolment_class', 'customer')


class PaymentRecord(models.Model):
    """
    缴费记录表
    """
    pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
    paid_fee = models.IntegerField("费用数额", default=0)
    note = models.TextField("备注", blank=True, null=True)
    date = models.DateTimeField("交款日期", auto_now_add=True)
    course = models.CharField("课程名", choices=course_choices, max_length=64, blank=True, null=True, default='N/A')
    class_type = models.CharField("班级类型", choices=class_type_choices, max_length=64, blank=True, null=True,
                                  default='N/A')
    enrolment_class = models.ForeignKey('ClassList', verbose_name='所报班级', blank=True, null=True, on_delete=models.CASCADE)
    customer = models.ForeignKey('Customer', verbose_name="客户", on_delete=models.CASCADE)
    consultant = models.ForeignKey('UserProfile', verbose_name="销售", on_delete=models.CASCADE)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    status_choices = (
        (1, '未审核'),
        (2, '已审核'),
    )
    status = models.IntegerField(verbose_name='审核', default=1, choices=status_choices)

    confirm_date = models.DateTimeField(verbose_name="确认日期", null=True, blank=True)
    confirm_user = models.ForeignKey(verbose_name="确认人", to='UserProfile', related_name='confirms', null=True,
                                     blank=True, on_delete=models.CASCADE)


class CourseRecord(models.Model):
    """课程记录表"""
    day_num = models.IntegerField("节次", help_text="此处填写第几节课或第几天课程...,必须为数字")
    date = models.DateField(auto_now_add=True, verbose_name="上课日期")
    course_title = models.CharField('本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField('本节课程内容', max_length=300, blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
    homework_title = models.CharField('本节作业标题', max_length=64, blank=True, null=True)
    homework_memo = models.TextField('作业描述', max_length=500, blank=True, null=True)
    scoring_point = models.TextField('得分点', max_length=300, blank=True, null=True)
    re_class = models.ForeignKey('ClassList', verbose_name="班级", on_delete=models.CASCADE)

crm/views/teacher.py
from django.views import View
import time

from django.shortcuts import render, redirect, reverse, HttpResponse
from django.contrib import auth
from django.views.generic import ListView
from crm import models
from crm.forms import RegForm, CustomerForm, ConsultRecordForm, EnrollmentForm, classForm,CourseForm
from crm.models import Customer, ConsultRecord
from django.views import View
from django.db.models import Q
from utils.pagination import Pagination
from django.utils.safestring import mark_safe
from django.http import QueryDict
import copy
from django.db import transaction  # 事务
from django.conf import settings


# 班级展示
class ClassList(View):
    def get(self, request):
        q = self.get_seache_contion(['course', 'semester'])
        all_class = models.ClassList.objects.filter(q)

        # 获取路径
        query_params = self.get_query_params()

        # 分页应用
        page = Pagination(request, len(all_class), request.GET.copy())
        return render(request, 'crm/teacher/class_list.html',
                      {"all_class": all_class[page.start:page.end], 'pagination': page.show_li,
                       'query_params': query_params})

    def get_seache_contion(self, query_list):
        """模糊查询"""
        query = self.request.GET.get('query', '')

        q = Q()
        q.connector = 'OR'
        for i in query_list:
            q.children.append(Q(('{}__contains'.format(i), query)))  # 进行拼接
        return q

    def get_query_params(self):
        """ 获取添加按钮"""
        url = self.request.get_full_path()

        qd = QueryDict()
        qd._mutable = True
        qd['next'] = url
        query_params = qd.urlencode()

        return query_params


# 新增编辑
def classes(request, edit_id=None):
    obj = models.ClassList.objects.filter(id=edit_id).first()
    form_obj = classForm(instance=obj)
    title = '编辑班级' if obj else '新增班级'
    if request.method == 'POST':
        form_obj = classForm(request.POST, instance=obj)
        if form_obj.is_valid():
            form_obj.save()
            next = request.GET.get('next')
            if next:
                return redirect(next)
            return redirect(reverse('class_list'))
    return render(request, 'crm/form.html', {'title': title, 'form_obj': form_obj})

# 课程展示
class course_list(View):

    def get(self, request, class_id):
        q = self.get_seache_contion([])
        all_course = models.CourseRecord.objects.filter(q, re_class_id=class_id)

        # 获取路径
        query_params = self.get_query_params()

        # 分页应用
        page = Pagination(request, len(all_course), request.GET.copy())
        return render(request, 'crm/teacher/course_list.html', {"all_course": all_course[page.start:page.end], 'pagination': page.show_li,'query_params': query_params})

    def get_seache_contion(self, query_list):
        """模糊查询"""
        query = self.request.GET.get('query', '')

        q = Q()
        q.connector = 'OR'
        for i in query_list:
            q.children.append(Q(('{}__contains'.format(i), query)))  # 进行拼接
        return q

    def get_query_params(self):
        """ 获取添加按钮"""
        url = self.request.get_full_path()

        qd = QueryDict()
        qd._mutable = True
        qd['next'] = url
        query_params = qd.urlencode()

        return query_params


# 新增编辑
def course(request, edit_id=None):
    obj = models.CourseRecord.objects.filter(id=edit_id).first()
    form_obj = CourseForm(instance=obj)
    title = '编辑课程' if obj else '新增课程'
    if request.method == 'POST':
        form_obj = classForm(request.POST, instance=obj)
        if form_obj.is_valid():
            form_obj.save()
            next = request.GET.get('next')
            if next:
                return redirect(next)
            return redirect(reverse('class_list'))
    return render(request, 'crm/form.html', {'title': title, 'form_obj': form_obj})

templates/crm/consultant/add_consult.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">添加客户</div>
        <div class="panel-body">

            <div class="col-sm-8 col-sm-offset-2">
                <form action="" method="post" novalidate>

                {% for field in form_obj %}
                    <div class="form-group row {% if field.errors %}has-error{% endif %}">
                        <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                        <div class="col-sm-10">{{ field }}<span class="help-block">{{ field.errors.0 }}</span></div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">提交</button>
                    </div>
                </div>
            </form>
            </div>
        </div>

    </div>
{% endblock %}

templates/crm/consultant/add_custmoer.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">添加客户</div>
        <div class="panel-body">

            <div class="col-sm-8 col-sm-offset-2">
                <form action="" method="post" novalidate>

                {% for field in form_obj %}
                    <div class="form-group row {% if field.errors %}has-error{% endif %}">
                        <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                        <div class="col-sm-10">{{ field }}<span class="help-block">{{ field.errors.0 }}</span></div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">提交</button>
                    </div>
                </div>
            </form>
            </div>
        </div>

    </div>
{% endblock %}

templates/crm/consultant/consult_record_list.html
{% extends 'layout.html' %}
{% block css %}
    <style>
        th, tr {
            text-align: center;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">Panel heading</div>
        <div class="panel-body">
            <a href="{% url 'add_record' %}" class="btn btn-primary btn-group-sm">添加</a>
            {#        {{ add_btn }}#}
            <div>
                <form action="" method="get" class="form-inline pull-right">
                    <input type="text" name="query" placeholder="模糊查询">
                    <button class="btn btn-sm btn-primary">搜索 <i class="fa fa-search"></i></button>
                </form>
            </div>

            <table class="table tab-content table-hover table-bordered">
                <thead>
                <tr>
                    <th>选择</th>
                    <th>序号</th>
                    <th>咨询客户</th>
                    <th>跟进内容</th>
                    <th>状态</th>
                    <th>跟进人</th>
                    <th>跟进日期</th>
                    <th>编辑</th>
                </tr>
                </thead>
                <tbody>
                {% for record in all_consult_record %}
                    <tr>
                        <td><input type="checkbox" name="id" value="{{ customer.id }}"></td>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ record.customer }}</td>
                        <td>{{ record.note }}</td>
                        <td>{{ record.get_status_display }}</td>
                        <td>{{ record.consultant }}</td>
                        <td>{{ record.date }}</td>
                        <td><a href="{% url 'edit_record' record.id %}"><i class="fa fa-edit fa-fw"></i></a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>


            <div style="text-align: right">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {{ pagination }}
                    </ul>
                </nav>
            </div>


        </div>
    </div>

{% endblock %}

templates/crm/consultant/custmoer.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            {% if edit_id %}
                编辑客户
            {% else %}
                添加客户
            {% endif %}
        </div>
        <div class="panel-body">

            <div class="col-sm-8 col-sm-offset-2">
                <form action="" method="post" novalidate>
                {% csrf_token %}
                {% for field in form_obj %}
                    <div class="form-group row {% if field.errors %}has-error{% endif %}">

                        <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                        <div class="col-sm-10">{{ field }}<span class="help-block">{{ field.errors.0 }}</span></div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">提交</button>
                    </div>
                </div>
            </form>
            </div>
        </div>

    </div>
{% endblock %}

templates/crm/consultant/customer_list.html
{% extends 'layout.html' %}
{% block css %}
    <style>
        th,tr {
            text-align: center;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">Panel heading</div>
        <div class="panel-body">
            <a href="{% url 'add_custmoer' %}" class="btn btn-primary btn-group-sm">添加</a>
{#        {{ add_btn }}#}
            <div>
                <form action="" method="get" class="form-inline pull-right">
                    <input type="text" name="query" placeholder="模糊查询">
                    <button class="btn btn-sm btn-primary">搜索 <i class="fa fa-search"></i></button>
                </form>
            </div>

            <form action="" method="post" class="form-inline">
                {% csrf_token %}
                <select name="action" class="form-control" style="margin: 5px 0">
                    <option value="">请选择</option>
                    <option value="multi_apply">放入私户</option>
                    <option value="multi_plu">放入公户</option>
                </select>
                <button class="btn btn-success btn-sm ">提交</button>
                <table class="table tab-content table-hover table-bordered">
                    <thead>
                    <tr>
                        <th>选择</th>
                        <th>序号</th>
                        <th>QQ</th>
                        {#                <th>QQ昵称</th>#}
                        <th>姓名</th>
                        <th>性别</th>
{#                        <th>手机号</th>#}
                        <th>客户来源</th>
                        <th>咨询课程</th>
                        <th>班级类型</th>
                        <th>状态</th>
                        {#                <th>咨询日期</th>#}
                        <th>最后跟进日期</th>
                        <th>销售</th>
                        <th>已报班级</th>
                        {% if request.path == '/crm/my_customer/' %}
                            <th>跟进记录</th>
                            <th>报名记录</th>
                        {% endif %}

                        <th>编辑</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for customer in all_customer %}
                        <tr>
                            <td><input type="checkbox" name="id" value="{{ customer.id }}"></td>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ customer.qq }}</td>
                            {#                    <td>{{ customer.qq_name |default:'暂无' }}</td>#}
                            <td>{{ customer.name |default:'暂无' }}</td>
                            <td>{{ customer.get_sex_display }}</td>
{#                            <td>{{ customer.phone |default:'暂无' }}</td>#}
                            <td>{{ customer.get_source_display }}</td>
                            <td>{{ customer.course }}</td>
                            <td>{{ customer.get_class_type_display }}</td>
                            <td>
                                {#                        {{ customer.status }}#}
                                {#                        <span style="background-color: dodgerblue; color: white; padding: 3px">未报名</span>#}
                                {{ customer.show_status|safe }}
                            </td>
                            {#                    <td>{{ customer.date }}</td>#}
                            <td>{{ customer.last_consult_date }}</td>
                            <td>{{ customer.consultant }}</td>
                            <td>{{ customer.show_classes }}</td>
                            {% if request.path == '/crm/my_customer/' %}
                                <td><a href="{% url 'consult_record'  customer.id%}">查看跟进记录</a></td>
                                <td><a href="{% url 'add_enrollment'  customer.id%}">添加报名记录</a></td>
                            {% endif %}

                            <td><a href="{% url 'edit_custmoer' customer.id %}?{{ query_params }}"><i class="fa fa-edit fa-fw"></i></a></td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>

            </form>
        <div style="text-align: right">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {{ pagination }}
                </ul>
            </nav>
        </div>


        </div>
    </div>

{% endblock %}

templates/crm/consultant/edit_consult.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">编辑跟进记录</div>
        <div class="panel-body">

            <div class="col-sm-8 col-sm-offset-2">
                <form action="" method="post" novalidate>

                {% for field in form_obj %}
                    <div class="form-group row {% if field.errors %}has-error{% endif %}">
                        <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                        <div class="col-sm-10">{{ field }}<span class="help-block">{{ field.errors.0 }}</span></div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">提交</button>
                    </div>
                </div>
            </form>
            </div>
        </div>

    </div>
{% endblock %}

templates/crm/consultant/edit_custmoer.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">编辑客户</div>
        <div class="panel-body">

            <div class="col-sm-8 col-sm-offset-2">
                <form action="" method="post" novalidate>

                {% for field in form_obj %}
                    <div class="form-group row {% if field.errors %}has-error{% endif %}">
                        <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                        <div class="col-sm-10">{{ field }}<span class="help-block">{{ field.errors.0 }}</span></div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">提交</button>
                    </div>
                </div>
            </form>
            </div>
        </div>

    </div>
{% endblock %}

templates/crm/consultant/edit_enrollment.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">编辑客户</div>
        <div class="panel-body">

            <div class="col-sm-8 col-sm-offset-2">
                <form action="" method="post" novalidate>

                {% for field in form_obj %}
                    <div class="form-group row {% if field.errors %}has-error{% endif %}">
                        <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                        <div class="col-sm-10">{{ field }}<span class="help-block">{{ field.errors.0 }}</span></div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">提交</button>
                    </div>
                </div>
            </form>
            </div>
        </div>

    </div>
{% endblock %}

templates/crm/consultant/enrollment.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">添加报名记录</div>
        <div class="panel-body">

            <div class="col-sm-8 col-sm-offset-2">
                <form action="" method="post" novalidate>

                {% for field in form_obj %}
                    <div class="form-group row {% if field.errors %}has-error{% endif %}">
                        <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                        <div class="col-sm-10">{{ field }}<span class="help-block">{{ field.errors.0 }}</span></div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">提交</button>
                    </div>
                </div>
            </form>
            </div>
        </div>

    </div>
{% endblock %}